### ISSUE TITLE
Text Replacer can send invalid messages.

### ISSUE THREAD

**Issue by SnowboundCabin** [MahdeenSky/BDPlugins#8]
If Text Replacer replaces the entire message with something like a single space, the message still gets sent, rather than blocked client-side as the manual equivalent would. This results in an error along the lines of "you may not share a server with the recipient, or they may have blocked you." (Yes, this happens in all channels, not just DMs.)

**Comment by MahdeenSky** [comment]
With the way the plugin is coded, I'm not quite sure how to prevent Discord from sending the message, so I resolved it by sending a zero-width space instead (still looks empty) but hey atleast discord doesn't block the message if it's empty after getting replaced.

Fixed with 53e8b60b1c229f80d2b8d1ca2619a1bc10a5e0b6
